service: ta-api
app: ta-api
org: fanciestw

plugins:
  - serverless-offline

package:
  exclude:
    - nodemon.json
    - README.md
    - .vscode/**
    - eslintrc.json

provider:
  name: aws
  runtime: nodejs10.x
  tags:
    AppName: 'ta-api'
    Owner: 'wlin26@yahoo.com'

functions:
  ta-api-admin:
    name: 'ta-api-admin'
    description: 'Lambda function for admin features for the TA Site'
    runtime: nodejs12.x
    handler: src/admin.handler
    events:
      - http: GET /api/announcements
      - http: POST /api/announcements

  app:
    handler: src/index.handler
    timeout: 20
    events:
        - http: GET /events
        - http: GET /announcements
        - http: 'ANY {proxy+}'
