service: ta-api
app: ta-api
org: fanciestw

provider:
  name: aws
  runtime: nodejs10.x
  tags:
    AppName: 'ta-api'
    Owner: 'wlin26@yahoo.com'

functions:
  app:
    handler: src/index.handler
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
