service: ta-api
app: ta-api
org: fanciestw

package:
  exclude:
    - node_modules/**
    - nodemon.json
    - README.md
    - .vscode/**
    - eslintrc.json

provider:
  name: aws
  runtime: nodejs10.x
  tags:
    AppName: 'ta-api'
    Owner: 'wlin26@yahoo.com'

functions:
  app:
    handler: src/index.handler
    timeout: 20
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'
